### ISSUE TITLE
 testCreatePkcs12 FAILED

### ISSUE THREAD

**Issue by egobsv** [nordic-institute/X-Road#1004]
Hi, I am trying to build 6.26 on Ubuntu 20, the build_packages script returns this error:
```
> Task :common-util:test

ee.ria.xroad.common.util.CertUtilsTest > testCreatePkcs12 FAILED
    java.security.KeyStoreException at CertUtilsTest.java:119
        Caused by: java.security.UnrecoverableKeyException at CertUtilsTest.java:119
            Caused by: java.security.NoSuchAlgorithmException at CertUtilsTest.java:119
212 tests completed, 1 failed
```
Further debug info shows:
```
NoSuchAlgorithmException unrecognized algorithm name: PBEWithSHA1AndDESede
```
Same error pops up using version 6.25.
Please advice.

Thank you,
Eric.

**Comment by petkivim** [comment]
Hi Eric,

The problem is caused by a bug in JDK 1.8.0u292. More detailed description of the bug can be found [here](https://bugs.openjdk.java.net/browse/JDK-8156584).

The `dev` branch already contains a [workaround](https://github.com/nordic-institute/X-Road/commit/8ce7e4d383d1de7a7a5fafa2c28f2ccea3e62c47) for the bug. Applying the workaround to the `6.26.0`  tag should  fix the problem.

Best regards,
Petteri

**Comment by egobsv** [comment]
that worked, thank you!
