### ISSUE TITLE
Support for Docker/Podman in Production for Central and Security Server

### ISSUE THREAD

**Issue by YBinMohamed** [nordic-institute/X-Road#1124]
In my setup, I tried using various installation option to familiarize with the setups.
I noticed that when using docker/podman for Central Server using systemd Ubuntu image, there's always the "global configuration error" that does not go away and the xroad-confclient service never stopped as it should. Manually stopping it does not help.

The entire issue goes away if I run the docker/podman with privileged option.

I checked the pre-built docker (https://hub.docker.com/r/niis/xroad-central-server) that I had setup at the beginning and although this does not have systemd, the X-Road is able to run.

I am unable to find any documentation for a Production friendly container setup (without privileged option being used) and I now am wondering if a container solution for Central Server is official supported and endorsed by NIIS? If yes, is there any documentation on how to do this with and especially without systemd?

I am also started seeing some issue with a container-based Security Server without privileged option and also would like to know for Security Server, is a container solution officially supported and endorsed by NIIS? If yes, is there any documentation available?

**Comment by petkivim** [comment]
Hi @YBinMohamed 

Unfortunately, the [Central Server Docker image](https://hub.docker.com/r/niis/xroad-central-server) is not meant for production use. As it is stated on Docker Hub, the image is for testing and development purposes only:

> The central server images are strictly meant for testing and development purposes. Do not use it in production environment!

[Security Server Sidecar](https://hub.docker.com/r/niis/xroad-security-server-sidecar) is a containerized version of the Security Server that supports production use. It's is officially supported by NIIS. 

The `xroad` services are run inside the Security Server Sidecar container using supervisord as root, although the processes it starts are not. To avoid potential security issues, it is possible to set up Docker so that it uses Linux user namespaces, in which case root inside the container is not root (user id 0) on the host. For more information, see https://docs.docker.com/engine/security/userns-remap/.

**Comment by YBinMohamed** [comment]
Hi @petkivim 

Thanks for the quick reply!
For the Central Server, based on your reply and if I have understood correctly, can I safely conclude that only a Ubuntu host setup is supported for Production use, correct?

**Comment by petkivim** [comment]
You're welcome! Currently, the officially supported platforms for the Central Server are Ubuntu 18.04 LTS and 20.04 LTS. The officially supported platforms for different components are documented in the release notes:

https://confluence.niis.org/display/XRDKB/X-Road+v7.0.0+Release+Notes

**Comment by YBinMohamed** [comment]
Noted and thanks for the web link to the supported platform links. This will come in very handy.

We will also check out the Security Server Sidecar that you have shared for our setup and familiarization.
Thank you again for the quick replies.
