### ISSUE TITLE
Duplicate X-Road-Client headers

### ISSUE THREAD

**Issue by andopaju** [nordic-institute/X-Road#1177]
**Docker image**: niis/xroad-security-server-standalone:focal-7.0.0.

By providing duplicate X-Road-Client headers, security server will validate only the last header:
`curl -X GET "http://127.0.0.1:8080/r1/CS/ORG/1111/TestService/abc/debug" -H "X-Road-Client: CS/GOV/0000/FAKEID" -H "X-Road-Client: CS/ORG/1111/TestClient" -H "accept: application/json"`

But service provider receives both headers:
CS/GOV/0000/FAKEID (not existing)
CS/ORG/1111/TestClient (exists)

This may confuse service providers - no way to know which client actually sent the request.
Furthermore, if server applications read only first or last duplicate header (by default quite common) then requesting system can be faked.

Expected result:
Either extra headers are removed or documentation is clarified so providers must not trust X-Road-Client header from security server.

**Comment by petkivim** [comment]
Thank you for the feedback. Even if the issue was detected using Docker, it can be reproduced on all the platforms supported by the Security Server. It's the Security Server's default behavior.

Currently, it's possible to add one or more `X-Road-Client` headers to a REST request. When multiple `X-Road-Client` headers are present, the consumer Security Server uses the last header as a sender of the message - the message is signed using the sign certificate of the sender. If there's no sign certificate available for the member, sending the request fails.

Similarly, the provider Security Server uses the last `X-Road-Client` header to [verify](https://github.com/nordic-institute/X-Road/blob/0e4be8110c842833e2e08d872914c3774f69ea62/src/common-verifier/src/main/java/ee/ria/xroad/common/signature/SignatureVerifier.java#L277-L289) the message sender. The value of the last `X-Road-Client` header must match with the client ID in the sign certificate that was used to sign the message. If the client IDs don't match, an error message is returned. Therefore, it's guaranteed that the sender of the message is defined by the last `X-Road-Client` header in the request.

In case there's a rogue/modified Security Server on the consumer side that changes the order of the client headers (e.g., puts the real sender first and a fake sender last), the message will fail the verification on the producer side since the client ID in the sign certificate that was used to sign the message doesn't match with the value of the last `X-Road-Client` header. 

All in all, providers can trust that the last `X-Road-Client` header in the request reliably defines the sender of the message. The documentation will be clarified for cases where multiple `X-Road-Client` headers are present in the request.
