### ISSUE TITLE
Asking about the Management Central Server's Security?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#184]
Dear XRoad,

Why in the XRoad Center we have to install the Management Security Server and Monitoring Security Server?

Could you explain me about it?

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Dear Dara,

Management services are provided by the X-Road governing organization to manage Security Servers and Security Server clients. Management services are implemented as standard X-Road services following X-Road message protocol. The management Security Server is needed to publish the management services so that other Security Servers are able to access them. Implementing the management Security Server is mandatory.

Security Server that is used for monitoring can be the same Security Server that is used for publishing management services (=the management Security Server) or it can be a another Security Server. Collecting monitoring data centrally from Security Servers is recommended, but not mandatory which means that implementing it can also be skipped.

More information about different terms can be found at:

https://github.com/nordic-institute/X-Road/blob/develop/doc/terms_x-road_docs.md

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear Petteri,

How about the Central Server Management UI vs Security Server Management UI what is the different between them?

- Monitoring Security Server what will we install to be the Monitoring Security Server?
Thanks in advanced

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Dear Dara,

Central Server and Security Server are two separate components and they both have their own management UIs for management operations. More details about Central Server and Security Server and their roles can be found [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Architecture/arc-g_x-road_arhitecture.md).

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Thanks Petteri.
