### ISSUE TITLE
Get Error when install Xroad-CS version 6.16 on ubuntu 14.04.6 LTS 64bit

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#217]
Dear @petkivim.

When i install Xroad-CS version 6.16 on server **(OS: ubuntu 14.04.6 LTS 64bit)**, i get error after run command: sudo apt-get install xroad-centralserver
**Error:**
ubuntu@ubuntu:~$ sudo apt-get install xroad-centralserver
_Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xroad-centralserver : Depends: xroad-center but it is not going to be installed
E: Unable to correct problems, you have held broken packages._

- I try install on other server(OS: ubuntu 14.04.6 LTS 64bit), i get the same error. I install follow link: https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md

Can you help me that error?

Best Regards,
trungnv

**Comment by petkivim** [comment]
Dear @trungnv0412 

X-Road version 6.16 is not officially supported anymore. The supported versions are 6.19.x, 6.20.x and 6.21.x. In addition, it is not currently possible to install any of the supported versions on Ubuntu 14.04 LTS host, because some of the dependencies required by X-Road have been removed from the official package repositories. This is because Ubuntu 14.04 LTS is not officially supported anymore and does not receive updates either. Therefore, it should no longer be used.

Installing X-Road versions are 6.19.x, 6.20.x and 6.21.x on Ubuntu 18.04 LTS works normally instead.

Best regards,
Petteri

**Comment by trungnv0412** [comment]
Thank @petkivim!

I have an XRoad System Version 6.16 which includes:
2 CS (HA)
4 SS
I want to install a backup for this system but the version 6.16 no longer supports. In this case, what should I do?
Is this OK if I install XRoad Version 6.12 and import 6.16's configurations?

Best Regards,
trungnv

**Comment by petkivim** [comment]
Hi @trungnv0412 

The safest route to arrive to the latest version and Ubuntu 18.04 is:

1. Take backup
2. On Ubuntu 14, upgrade the X-Road software step by step: 6.16 -> 6.17 -> 6.19.1 -> 6.21.1
3. Upgrade Ubuntu 14 to Ubuntu 18 ([in-place](https://confluence.niis.org/pages/viewpage.action?pageId=12484642) or [using backup](https://confluence.niis.org/pages/viewpage.action?pageId=12484639))

Best regards,
Petteri

**Comment by trungnv0412** [comment]
@petkivim  Thank you very much! I will try it.
