### ISSUE TITLE
Asking about the Server Code?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#274]
Dear XRoad,

If our Security has two IP address How to configure that?

![image](https://user-images.githubusercontent.com/8038324/69774074-6e01d780-11c7-11ea-9d39-4763c78fe924.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

X-Road supports only one IP address or FQDN per Security Server - X-Road does not enable configuring two IP addresses or FQDNs for a single Security Server. 

As a workaround, you could solve the problem on DNS level. You could configure multiple IP addresses for the same A record, and then register the Security Server using the FQDN.

Best regards,
Petteri

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
Could I ask you one more question about the OCSP Responder if we use the OCSP Responder with Two Way TLS Connection what should I do how upload the JKS file to the Central Server?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Security Server's OCSP client uses Java’s default truststore. Therefore, in case OCSP responses are fetched over HTTPS, the OCSP responder’s TLS certificate must be issued by a CA which root certificate is available in the truststore. If the root certificate is not available in the truststore it must be installed on the Security Server following the steps described here:

https://confluence.niis.org/pages/viewpage.action?pageId=4292906

In case mutual TLS is used, you must create a keystore on the Security Server and use system parameters to define it's location. OCSP client’s private key + certificate must be stored in the keystore. However, using mutual TLS in the connection between Security Server and OCSP responder causes significant configuration overhead which is why you might want to consider using one way TLS instead.

Best regards,
Petteri
