### ISSUE TITLE
Production ready docker images

### ISSUE THREAD

**Issue by Rauno56** [nordic-institute/X-Road#308]
> The security server images are strictly meant for testing and development purposes. Do not use it in production environment!

Is there a fundamental reason why running the security server from a container in a production environment cannot be done?

**Comment by petkivim** [comment]
According to the Docker best practices each container should have only one concern and run only  a single process. The Security Server consists of multiple processes including a PostgreSQL database, and the currently available Docker image runs them all in a single container.

In addition, the image contains the internal key and certificate of the Security Server which means that every container started from the image uses the same internal key and certificate. This makes the containers vulnerable to MITM attacks.  In a production level implementation there would be a mechanism to recreate the internal key and certificate when a new container is started so that the key and certificate are unique for each container.

There's an ongoing project which goal is to implement a production level Security Server Docker image that can be run as a side car. Currently the project is at PoC stage. More information about the project can be found at:

https://github.com/nordic-institute/X-Road-Security-Server-sidecar/

Regards,
Petteri

**Comment by Rauno56** [comment]
Thanks for the quick reply, Petteri.

Those best practices are good to follow for sure. They are not always the only way to go, however. If done cautiously, the best practices allow flexibility. Main reasons to have that specific best practice are not necessarily applicable to this system - the parts share an isolation boundary in a recommended deployment scenario, are scaled together, etc. Logging is an issue that pops to mind with having multiple processes. 🤔

Having PostgreSQL instance outside of the container is a must and, as I understand from the setup documentation, trivial to achieve. Although, I fully agree that the way the image is built currently is not production-ready in that regard. Could we offer a simple way to use an external PG instance as a default in another image?

Another thing to be solved is the state on the machines - basically, the location of everything that comes exported with a backup bundle(config, certs, Nginx configs, logs, ...) and the storage location of the backup snapshots themselves has to be configurable. That might not be a thing with the sidecar.

Thanks for the reference, I'll check it out.

**Comment by petkivim** [comment]
You're right, strictly following the best practices is not the only way to go and therefore, the aim is not to deploy every Security Server process in its own container. The aim is to enable deploying the Security Server application and database separately. The Security Server already supports using a remote database that can be another Docker container, managed DB service on the cloud etc. However, the Docker image must be made configurable so that the user can define the connection details, the Security Server creates the db in case it does not exist yet etc. This in the further enhancements list for the project.

When it comes to the X-Road application logs, they can be redirect logging to console so that "docker logs" can be used to view the logs.

**Comment by Rauno56** [comment]
Could one potentially move all the state (postgres data folder and on-disk versions of the files that are included in the backup) onto a persistent disc volume(in the context of Kubernetes) and have the main container stateless that way?

**Comment by petkivim** [comment]
Yes, that should basically work, but please note that it has not been tested and it is not officially supported. In addition, there are some other things to be considered:

- Message log archives are stored on the disk and they are not included in the backup. The directory where they are stored should be mounted to a persistent disk volume too.
- How to run the upgrade logic when the docker image has been updated and it is necessary to run e.g. db migrations.
- Security server has fixed memory parameters. Heap size should adapt to memory allocated to the container.
- Proxy health check interface should be configured and exposed so that Kubernetes (`livenessProbe`) can check that the proxy is up and running.

In addition, the following security aspects should be considered when multiple Security Servers with different identities are created from the same image:

- When a new container is created from the image internal server certificates must be generated so that the certs are unique per container.
- When a new container is created from the image `serverconf` database user(s) must be generated so that the passwords are unique to container  (optionally passed as parameter).
- When a new container is created from the image the security server admin user and password must be changed so that they are unique per container.

**Comment by petkivim** [comment]
I’m closing this issue now, but in case you require any assistance in the future, please open a new issue.
