### ISSUE TITLE
Systemd Unit file for xroad-proxy uses feature unavailable in EL7

### ISSUE THREAD

**Issue by mbert** [nordic-institute/X-Road#384]
The X-Road RPMs are supposed to support EL7. However the file xroad-proxy.service contains the following line:

``
AmbientCapabilities=CAP_NET_BIND_SERVICE
``

This makes the service start fail with `status=218/CAPABILITIES`. According to what I have found the above line works only with systemd versions of 230 upwards. However EL7 is still at systemd 219. 

From what I have seen this feature does not seem to be necessary, at least not for the default configuration, where you would run the proxy on ports 8080 and 8443 respectively (rather than 80/443). Hence it _seems_ (correct me if I'm wrong) sound to just comment this out. However the service should really work out of the box on EL7, shouldn't it?

**Comment by petkivim** [comment]
Which RHEL 7 version you're using? Security Server requires version RHEL 7.3 or newer. Ambient capabilities are available starting from version 7.3 ([release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.3_release_notes/index)).

The feature is not necessary for running Security Server since it's used only if you want to use ports `80` / `443` instead of ports `8080` / `8443`. However, there are other features too that require RHEL 7.3 or newer.

Best regards,
Petteri

**Comment by mbert** [comment]
We are using Oracle Linux 7.7, and I have also been able to reproduce the problem with CentOS 7.7.

**Comment by mbert** [comment]
Does RHEL 7.3 have systemd version >= 230?

**Comment by petkivim** [comment]
The supported operating systems for Security Server are Ubuntu 18.04 LTS and RHEL7 (7.3 or newer). Unfortunately, Oracle Linux and CentOS are not officially supported. Instead, Central Server supports only Ubuntu 18.04 LTS.

I'm not sure which version of systemd RHEL7.3 has, but according to the release notes ambient capabilities are supported:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.3_release_notes/index

**Comment by mbert** [comment]
Both CentOS and Oracle Linux are RHEL derivates. What runs on RHEL will run on its derivates, too (by the way, you build rpm packages in a CentOS 7 docker container). 

I have quickly checked, RHEL 7.3 uses the same systemd version, 719. Ambient capabilities are not unsupported, but it seems like the `CAP_NET_BIND_SERVICE` capability is. 

I would be very surprised if the service can be run on RHEL 7.3 with the xroad-proxy.service file as it is now. The change with that line came in 9264dfc61399f663f81fca3bd37caa429dfa325b, that was October last year. I would not rule out that this has never been tested on an EL7 system.

**Comment by petkivim** [comment]
I tested installing Security Server on RHEL 7.3, and the proxy service started normally without problems. The systemd version was 219. I did the test on AWS using this AMI:

RHEL-7.3_HVM-20170613-x86_64-4-Hourly2-GP2 (ami-0e258161)

We run automated tests on all the supported operating systems as a part of our CI pipeline so every release is tested on the supported platforms. Even if CentOS and Oracle Linux are RHEL derivates, we do not officially support them. In practice, the software most likely works with them, but we can not guarantee it since we have not tested it.

**Comment by mbert** [comment]
Thank you. This is indeed weird, in particular since we are using both OEL and CentOS in versions far above 7.3. I'll try to exploit my contact at Oracle and report any findings here.

**Comment by mbert** [comment]
Having checked again, the problem seems to be exclusive to Oracle Linux. Once I have found something conclusive I'll drop it here and close this issue.

**Comment by petkivim** [comment]
Thanks for the update! Yes, please let us know what caused the issue so that we know the reason in case someone else reports about a similar issue in the future.

**Comment by mbert** [comment]
The problem could be solved. It works on Oracle Linux with the latest kernel from the `ol7_UEKR5` repository. That repository seems to be deactivated by default (it was on our machines) so that our systems were running a kernel version 4.1.12 with which the issue occurred. After an upgrade to the latest kernel from the above repo (4.14.35) the `CAP_NET_BIND_SERVICE` capatility was accepted. 
I am closing this issue, hoping that it may help others running into similar issue, thank you for your support!

**Comment by petkivim** [comment]
Thanks for the update and sharing the solution. It's good to hear that the problem was resolved.
