### ISSUE TITLE
REST adapter service problem when calling between two Security Servers

### ISSUE THREAD

**Issue by ngolongquan** [nordic-institute/X-Road#471]
Hi, X-Road support team,
I’ve install the X-Road (version 6.23 Ubuntu 18.04) with following info:
-	Central Admin
 ![ca](https://user-images.githubusercontent.com/60766273/79822456-61229200-83bb-11ea-8b18-3548a9c85208.png)
-       Security Server (SS1)
![ss1](https://user-images.githubusercontent.com/60766273/79822477-6da6ea80-83bb-11ea-918e-501886debb27.png)

-	Security Server (SS2)
 ![ss2](https://user-images.githubusercontent.com/60766273/79822446-5b2cb100-83bb-11ea-9c00-eca2ccde9812.png)

In SS2 I configue REST API and grant ACCESS RIGHT for SUBSYSTEM of SS1
![rest acl](https://user-images.githubusercontent.com/60766273/79822485-75ff2580-83bb-11ea-9602-dc6e90582d3a.png)

 But when I make request to the API below:
curl -i -X GET "http://10.50.0.80/r1/VNU/VNU/5678/ORG_1/respa/unit/" -H "accept: application/json" -H "X-Road-Client: VNU/VNU/1234/ORG_1"
The error message shows: {"type":"Server.ClientProxy.UnknownMember","message":"Client 'SUBSYSTEM:VNU/VNU/1234/ORG_1' not found"}
Please help me fix this isssue.

**Comment by petkivim** [comment]
Hi @ngolongquan 

You're using `VNU/VNU/1234/ORG_1` as client which means that the request must be sent to SS1, not to SS2. If you want to use SS2 as consumer Security Server, you must use `VNU/VNU/5678/ORG_1` as client.

The subsystem that you use as client must be registered on the consumer Security Server. Otherwise `Server.ClientProxy.UnknownMember` error is returned.

Regards,
Petteri

**Comment by ngolongquan** [comment]
Hi @petkivim ,
Thanks for your answer.
I've just change request URL to curl -i -X GET "http://10.50.0.80/r1/VNU/VNU/5678/ORG_1/respa/unit/" -H "accept: application/json" -H "X-Road-Client: VNU/VNU/1234/ORG_1
Everything is OK.
Many thanks!!!
I close this issue right now.
