### ISSUE TITLE
Asking help with Loggable size is exceeds?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#494]
Dear @petkivim ,

`LoggingFailed: Message size exceeds maximum loggable size`

Could I ask this error?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Is the error caused by a REST message which body size exceeds 10MB? By default the maximum loggable body size for REST messages is set to 10MB. You can increase the limit by overriding the `max-loggable-body-size` property value in the `/etc/xroad/conf.d/local.ini` file. Another alternative is to set the `truncated-body-allowed` property to ` true` which causes the message body to be truncated in messagelog in case the body size exceeds the maximum limit. More information about the properties can be found at:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-syspar_x-road_v6_system_parameters.md#37-message-log-add-on-parameters-message-log 

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim,

Could you suggest the value of these two parameters?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The values depend on your requirements. Do you need to be able to verify the signature of every message afterwards? If the answer is yes, then you must keep `truncated-body-allowed=false` and increase the value of `max-loggable-body-size` so that it covers all processed messages. In case you do not need to be able to verify the signature of every message afterwards, just set `truncated-body-allowed=true` and keep the value of `max-loggable-body-size` as it is now.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim,

Thanks for your advice.

Best Regards, 
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question related to the build Packages? If our Security Server Member they want to build their own Packages and they don't want to use our Release packages. Is it possible to check it to make sure they will use the same source code to build it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Unfortunately, there's no way to verify that they have used the same unmodified code base to compile the packages. It's possible to check the version number using [environmental monitoring](https://github.com/nordic-institute/X-Road/blob/develop/doc/EnvironmentalMonitoring/Monitoring-architecture.md), but that does not guarantee that the code has not been modified. One alternative is to forbid the use of other than the official packages in your environment - even if you have limited tools to monitor it.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your advice.

Best Regards,
Dara Penhchet
