### ISSUE TITLE
Asking help about the handshake failure

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#547]
Dear @petkivim ,

Could you help to check this error?
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.IOError: Received fatal alert: handshake_failure

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Based on the error code (`Server.ServerProxy.IOError`) the error is generated by the provider side Security Server, and it seems that the SSL handshake between the provider side Security Server and the service fails. Have you checked the proxy log for details?

One potential reason for the problem is that the service does not support any of the cipher suites that the Security Server supports by default. The Security Server supports TLS 1.2 and cipher suites listed below:

- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256*
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256*
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384*
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384*
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
- TLS_DHE_RSA_WITH_AES_256_GCM_SHA384

(*) Not supported in RHEL when OpenJDK is used.

In case this is the problem, the solution is to update the configuration so that there's a cipher suite that's supported by both the Security Server and the service. More information about changing the Security Server's configuration can be found [here](https://confluence.niis.org/pages/viewpage.action?pageId=4292898).

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I have used the Cloudflare SSL Certificate so what should I change in my nginx and security server?

Best Regard,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

First, you should check the configuration of your Nginx and verify that is supports one of the  cipher suites that are supported by the Security Server. If that's not currently the case, that you must update the configuration so that there's a cipher suite that's supported by both the Security Server and Nginx.

In case your Nginx required two-way authentication in SSL, you must also upload Nginx's certificate to the Security Server. Uploading Nginx's certificate is done in the internal TLS certificate section (1) of the subsystem that you have used to publish your service on the provider side Security Server. If you need to add the Security Server's certificate to Nginx's configuration, it can be downloaded in the Security Server certificate section (2).

![Screenshot 2020-06-13 at 14 47 11](https://user-images.githubusercontent.com/575897/84567957-f3746000-ad84-11ea-837a-4244b24798cb.png)

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your information.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you about the Read Timeout with Rest Connection? Could I increase its timeout?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The timeout can be configured using the service parameters:

![Screenshot 2020-06-16 at 8 01 57](https://user-images.githubusercontent.com/575897/84733727-b805ab80-afa7-11ea-968f-fcee956aeeec.png)

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your information.

Best Regards,
Dara Penhchet
