### ISSUE TITLE
Asking help about the Failed to register certificate: SocketException: Connection reset?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#599]
Dear @petkivim ,

The connection between security server and Central server is connected, but I still got this error?
`Failed to register certificate: SocketException: Connection reset?`

Do you have any ideas about this error?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

It's a networking issue and they are typically caused by incorrect firewall configurations. I would first verify one more time that:

1. The Security Server allows outgoing connections to the Central Server port 4001
2. The Central Server allows incoming connections to port 4001 from the Security Server

Depending on your network configuration the Security Server might have multiple public IP addresses. If this is the case, please make sure that you have enabled access to the Central Server port 4001 from the correct public IP address.

In addition, I would verify whether registering authentication certificate works from other Security Servers to understand is this a common issue or related to one specific Security Server only.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your advice. We have found the problem because the Security Server cannot connect to Central Server with port 4001.

Best Regards,
Dara Penhchet
