### ISSUE TITLE
Source not working properly

### ISSUE THREAD

**Issue by gudvardur** [nordic-institute/X-Road#672]
This line probably needs to be change from what it is to 
`source /etc/profile.d/rvm.sh`
https://github.com/nordic-institute/X-Road/blob/e1aebacc5a519a7f27f2f086bf6cc43fbfee384f/src/prepare_buildhost.sh#L22

Since it returned this error and aborted the script...
`./prepare_buildhost.sh: line 22: /root/.rvm/scripts/rvm: No such file or directory`

After changing to `source /etc/profile.d/rvm.s` it ran fine.

**Comment by gudvardur** [comment]
I guess this is not supported using root as build user. This worked fine when using other user.

**Comment by sagilar** [comment]
Hi,

It seems to be due to newer rvm versions.
I solved it by changing the update_ruby_dependencies.sh on line 11:
`#source ~/.rvm/scripts/rvm`  
`source "/etc/profile.d/rvm.sh"`  
as the [installation of rvm](https://github.com/rvm/ubuntu_rvm) on ubuntu suggests.

I also uninstalled the bulder version 2.1.4 and installed an older one (version 1.17.1), then it worked!

I hope it helps you,

regards,
Santiago.
