### ISSUE TITLE
Sizing Xroad

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#777]
Dear @petkivim!

Now, i want to calculate server configuration for setup xroad. I want know calculation formula CPU, RAM, HDD for CS, SS.Can you provide information about it for me?

Regards,
trungnv

**Comment by petkivim** [comment]
Hi @trungnv0412 

The minimum requirements are documented in the installation guides. Please note, that these are minimum requirements to run the components, not the recommended requirements for production workloads. 

- https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md#23-requirements-for-the-security-server
- https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#23-requirements-to-the-central-server

More information about disk space requirements for the Security Server logs can be found at:

https://confluence.niis.org/pages/viewpage.action?pageId=4293074

Regards,
Petteri

**Comment by trungnv0412** [comment]
Hi Petteri,
Thank you for your advice. Could you please tell me how to sizing production workloads? In particular, I need to know the formulas to calculate CPU, RAM, HDD on CS and SS.
For example, I am installing a system including 10 SS, 900 requests per minute for each SS. How should I sizing this system?

Regards,
trungnv

**Comment by petkivim** [comment]
Hi @trungnv0412 

We don't have official recommendations for production use since the sizing depends on many different factors that vary between use cases and hosting platforms. However, the Finnish Digital Agency has published some recommendations regarding the Security Server sizing. Unfortunately, the page is available in Finnish only, but with your preferred online translation service you should be able to get the information you need out of it:

https://palveluhallinta.suomi.fi/fi/tuki/artikkelit/591ea0eb14bbb10001966fcd

Regards,
Petteri

**Comment by trungnv0412** [comment]
Dear @petkivim 

Thank you very much!

Regards,
trungnv
