### ISSUE TITLE
About opmonitor and parameter xroad-tls-ciphers in proxy.ini

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#810]
Dear @petkivim !

I need your support.

**- Problem 1:**
I install Security Server version 6.23 but not see xroad-opmonitor service. How do enable opmonitor service?

**- Problem 2:**

In file: /etc/xroad/conf.d/proxy.ini have parameter xroad-tls-ciphers. I understand this parameter config xroad uses ciphers suit of Java for encode data between Security Servers. How do i use my ciphers suit to replace ciphers suit of Java? If you have documents about this ploblem, can you send me please?

**Comment by petkivim** [comment]
Hi @trungnv0412 

Please see below some comments and answers.

**Problem 1**

You have to install the operational monitoring add-on separately: `sudo apt-get install xroad-opmonitor`

**Problem 2**

In order to override the default values of system parameters, create or edit the file `/etc/xroad/conf.d/local.ini`. The parameter `xroad-tls-ciphers` can be overridden using the configuration below.

```
[proxy]
xroad-tls-ciphers=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
```
Changing a parameter value in the `/etc/xroad/conf.d/local.ini` file requires restarting the `xroad-proxy` service.

More information about supported ciphers can be found [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-syspar_x-road_v6_system_parameters.md#Ref_note2).

**Comment by trungnv0412** [comment]
Thank for your help!

**Comment by thaoqd** [comment]
Dear @petkivim 
I need your support.
I want to setup High Availability for Central Server on 02 server Ubuntu 14.04 with Central Server version 6.16. 
Please send for me installation guide for High Availability for Central Server 6.16.
Thanks

**Comment by petkivim** [comment]
Hi @thaoqd 

The high availability guide for the Central Server version 6.16.0 is available [here](https://github.com/nordic-institute/X-Road/blob/6.16.0/doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md).

**Please note that version 6.16.0 is not supported anymore.** Also, Ubuntu 14.04 is no longer supported and does not receive updates. Therefore, it is strongly recommended to upgrade to Ubuntu 18.04 or 20.04, and to a supported X-Road version (6.23, 6.24, 6.25). To upgrade to the latest version, you should follow these steps:

- First, read the [release notes](https://confluence.niis.org/display/XRDKB/Release+Notes).
- Before starting the upgrade process, take a full backup of both Central Server nodes.
- Then upgrade from version 6.16 to version 6.18.1.
- Then from version 6.18.1 to 6.20.1.
- After upgrading X-Road to version 6.20.1, upgrade the operating system from Ubuntu 14 to Ubuntu 18 following [these](https://confluence.niis.org/pages/viewpage.action?pageId=12484635) instructions.
- Then upgrade X-Road from 6.20.1 to 6.22.1.
- Then upgrade X-Road from 6.22.1 to 6.24.1, and finally from 6.24.1 to 6.25.0.

When upgrading to version 6.23.0 or later, please read these release notes very carefully:

https://confluence.niis.org/display/XRDKB/X-Road+v6.23.0+Release+Notes

The high availability support of the Central Server changed in version 6.23.0.

Regards,
Petteri
