### ISSUE TITLE
Problem when restore HA CS

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#817]
Dear @petkivim !

I have problem when restore HA CS. My System: 2 Server install HA CS, 1 master node and 1 slave node, this is running. Xroad version 6.16 and set up cluster DB use BDR. Now i will restore this system on new servers. The steps are as follows:

Step 1: I install HA CS on new servers  but not create infomation for CS.
Step 2: I download backup file from system is running and import that to new system. Backup from node_0 import to node_0, backup from node_1 import to node_1.

When I import to node_0 i have problem with BDR. I check xroad_bdr_replication_info on running system and restore system, it not the same.
- In running system:
![image](https://user-images.githubusercontent.com/55520717/103406608-dd49b800-4b8d-11eb-9eb1-70f2f2026b88.png)

- In restore system: 
![image](https://user-images.githubusercontent.com/55520717/103406655-0702df00-4b8e-11eb-9a96-5b251a956f67.png)

Can you support me for this ploblem? 

Thanks,
Trungnv

**Comment by petkivim** [comment]
Hi @trungnv0412 

Version 6.16 is not supported anymore. It's strongly recommended to upgrade to one of the currently supported versions (6.23, 6.24, 6.25). Unfortunately, the upgrade path is quite complicated, because the current version you're running is pretty old. The required steps for the upgrade are described [here](https://github.com/nordic-institute/X-Road/issues/810#issuecomment-750747474).

The Central Server HA Guide provides [instructions](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md#6-recovery-of-the-ha-cluster) for the recovery of the HA cluster. Have you been following the instructions?

Regards,
Petteri

**Comment by trungnv0412** [comment]
Thank @petkivim!
